services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dpp-fashion-api
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
    networks:
      - dpp-network

volumes:
  dpp-cache:

networks:
  dpp-network:
    driver: bridge
